apiVersion: v1
kind: ConfigMap
metadata:
  name: mdns-template
  namespace: {{ .HandlerNamespace }}
data:
  common-config.hcl.tmpl: |
    bind_address = "{{`{{ .NonVirtualIP }}`}}"
    collision_avoidance = "hostname"
    service {
        name = "{{`{{ .Cluster.Name }}`}} Workstation"
        host_name = "{{`{{ .ShortHostname }}`}}.local."
        type = "_workstation._tcp"
        domain = "local."
        port = 42424
        ttl = 3200
    }
