---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cluster-hosted-mdns
  namespace: {{ .HandlerNamespace }}
  labels:
    app: cluster-hosted
    component:  cluster-hosted-mdns
spec:
  selector:
    matchLabels:
      name: cluster-hosted-mdns
  template:
    metadata:
      labels:
        app: cluster-hosted
        component: cluster-hosted-mdns
        name: cluster-hosted-mdns
    spec:
      tolerations:
      - operator: "Exists"
      hostNetwork: true
      serviceAccountName: cluster-hosted-handler    
      volumes:
      - name: resource-dir
        configMap:
          name: mdns-template
          items:
          - key: "common-config.hcl.tmpl"
            path: "common-config.hcl.tmpl"
      - name: kubeconfig
        hostPath:
          path: "/etc/kubernetes/kubeconfig"
      - name: conf-dir
        empty-dir: {}
      initContainers:
      - name: cluster-hosted-verify-hostname
        image:  {{ .BaremetalRuntimeCfgImage }}
        command:
        - "/bin/bash"
        - "-c"
        - |
          #!/bin/bash
          set -xv
          function get_hostname()
          {
            if [[ -s $RUNTIMECFG_HOSTNAME_PATH ]]; then
              cat $RUNTIMECFG_HOSTNAME_PATH
            else
              # if hostname wasn't updated by NM script, read hostname
              hostname
            fi
          }
          while [[ "$(get_hostname)" =~ ^localhost(.localdomain)?$ ]]; do
            echo "hostname is still set to a default value"
            sleep 1
          done
        volumeMounts:
        - name: conf-dir
          mountPath: "/etc/mdns"
      - name: cluster-hosted-render-config-mdns-publisher
        image:  {{ .BaremetalRuntimeCfgImage }}
        command:
        - runtimecfg
        - render
        - "/etc/kubernetes/kubeconfig"
        - "--api-vip"
        - "{{ .OnPremPlatformAPIServerInternalIP }}"
        - "--ingress-vip"
        - "{{ .OnPremPlatformIngressIP }}"
        - "/config"
        - "--out-dir"
        - "/etc/mdns"
        - "--verbose"
        resources: {}
        volumeMounts:
        - name: kubeconfig
          mountPath: "/etc/kubernetes/kubeconfig"
        - name: resource-dir
          mountPath: /config/config.hcl.tmpl
          subPath: common-config.hcl.tmpl
        - name: conf-dir
          mountPath: "/etc/mdns"
        imagePullPolicy: IfNotPresent
      containers:
      - name: cluster-hosted-mdns-publisher
        image: {{ .MdnsPublisherImage }}
        args:
        - "--debug"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: conf-dir
          mountPath: "/etc/mdns"
        livenessProbe:
          exec:
            command:
            - pgrep
            - mdns-publisher
          initialDelaySeconds: 10
        terminationMessagePolicy: FallbackToLogsOnError
        imagePullPolicy: IfNotPresent
