apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-template
  namespace: {{ .HandlerNamespace }}
data:
  common-Corefile.tmpl: |
    .:5333 {
        errors
        health :18080
        mdns {{`{{.Cluster.Name}}`}}.{{`{{.Cluster.Domain}}`}} 0 {{`{{.Cluster.Name}}`}} {{`{{.NonVirtualIP}}`}}
        forward . {{`{{- range $upstream := .DNSUpstreams}} {{$upstream}}{{- end}}`}}
        cache 30
        reload
        template IN {{`{{ .Cluster.IngressVIPRecordType }}`}} {{`{{.Cluster.Name}}`}}.{{`{{.Cluster.Domain}}`}} {
            match .*.apps.{{`{{.Cluster.Name}}`}}.{{`{{.Cluster.Domain}}`}}
            answer "{{`{{"{{ .Name }}"}}`}} 60 in {{`{{"{{ .Type }}"}}`}} {{ .OnPremPlatformIngressIP }}"
            fallthrough
        }
        template IN {{`{{ .Cluster.IngressVIPEmptyType }}`}} {{`{{.Cluster.Name}}`}}.{{`{{.Cluster.Domain}}`}} {
            match .*.apps.{{`{{.Cluster.Name}}`}}.{{`{{.Cluster.Domain}}`}}
            fallthrough
        }
        template IN {{`{{ .Cluster.APIVIPRecordType }}`}} {{`{{.Cluster.Name}}`}}.{{`{{.Cluster.Domain}}`}} {
            match api.{{`{{.Cluster.Name}}`}}.{{`{{.Cluster.Domain}}`}}
            answer "{{`{{"{{ .Name }}"}}`}} 60 in {{`{{"{{ .Type }}"}}`}} {{ .OnPremPlatformAPIServerInternalIP }}"
            fallthrough
        }
        template IN {{`{{ .Cluster.APIVIPEmptyType }}`}} {{`{{.Cluster.Name}}`}}.{{`{{.Cluster.Domain}}`}} {
            match api.{{`{{.Cluster.Name}}`}}.{{`{{.Cluster.Domain}}`}}
            fallthrough
        }
    }
