---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-hosted-net-services-operator-images
  namespace: cluster-hosted-net-services-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
data:
  images.json: >
    {
      "baremetalRuntimecfg": "registry.svc.ci.openshift.org/openshift:baremetal-runtimecfg",
      "haproxyRouter": "registry.svc.ci.openshift.org/openshift:haproxy-router",
      "keepalivedIpfailover": "registry.svc.ci.openshift.org/openshift:keepalived-ipfailover",
      "mdnsPublisher": "registry.svc.ci.openshift.org/openshift:mdns-publisher",
      "coredns": "registry.svc.ci.openshift.org/openshift:coredns"
    }
