apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  name: cluster-hosted-net-services-operator
  namespace: cluster-hosted-net-services-operator
---
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: true
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: true
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  name: cluster-hosted-handler
  namespace: cluster-hosted-net-services-operator
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:cluster-hosted-net-services:cluster-hosted-handler
