apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-hosted-net-services-operator
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-hosted-net-services-operator
subjects:
- kind: ServiceAccount
  name: cluster-hosted-net-services-operator
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-hosted-net-services-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-hosted-net-services-operator
subjects:
- kind: ServiceAccount
  name: cluster-hosted-net-services-operator
  namespace: system
